parameters:
    locale: es
    path.root: fitness/public
    path.imagenes: /imagenes


twig:
    number_format:
        decimal_point: ','
        thousands_separator: '.'
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        root: '%path.root%'
        imagenes: '%path.imagenes%'