knp_snappy:
   pdf:
       enabled:    true
       binary:     /symfony/wkhtmltox/bin/wkhtmltopdf
       options:    []
   image:
       enabled:    true
       binary:     /symfony/wkhtmltox/bin/wkhtmltoimage
       options:    []