easy_admin:
    site_name: '<img src="/fitness/public/imagenes/fitnesConFondo.png">Fussion Fitnnes Gym'
    design:
        brand_color: '#e2048d'
        menu:
            # Entidades de Damian A
            - label: 'Gestión de alumnos'
              icon: 'address-card'
              children:
                - { entity: 'Alumno', icon: 'address-card' }
                - { entity: 'FichaMedica', icon: 'clipboard' }
                - { entity: 'Telefono', icon: 'phone' }
            # Entidades de Maxi
            - { label: "Actividades" , entity: 'Actividad', icon: 'bolt' }
            - label: 'Gestión de Inventario'
              icon: 'cogs'
              children:
                - { entity: 'Equipamiento', icon: 'cogs' }
                - { entity: 'Elemento', icon: 'list' }
            # Entidades de Emiliano
            - label: 'Gestión de Empleados'
              icon: 'users'
              children:
                - { entity: 'Empleado', icon: 'users' }
                - { entity: 'Profesor', icon: 'user' }
                - { entity: 'Telefono', icon: 'phone' }
            # Entidades de Matias
            - { label: "Usuarios" , entity: 'User', icon: 'child' }
            

    entities:
        # change the following to the namespaces of your own entities
        User:
            class: App\Entity\User 
        # Entidades de Damian
        Alumno:
            class: App\Entity\Alumno
            list:
                fields: [ { property: 'dni', label: 'DNI' }, 'apellido', 'nombre','balance']
            form:
                fields:
                    - { property: 'dni', type: 'text', label: 'DNI'}
                    - { property: 'apellido', type: 'text', label: 'Apellido'}
                    - { property: 'nombre', type: 'text', label: 'Nombres'}    
                    - { property: 'fechaNacimiento', type: 'date',type_options: {widget: 'single_text'}, label: 'Fecha de nacimiento'}
                    - { property: 'direccion', type: 'text', label: 'Dirección'}
                    - { property: 'localidad', type: 'text', label: 'Localidad'}
                    - { property: 'cp', type: 'text', label: 'Código Postal'}
                    - { property: 'observaciones', type: 'textarea', label: 'Observaciones'}
                    - { property: 'cuenta', type: 'text', label: 'Cuenta'}
                    - { property: 'correo', type: 'text', label: 'Correo electrónico'}
                    - { property: 'ocupacion', type: 'text', label: 'Ocupación'}
                    - { property: 'balance', type: 'money', label: 'Balance de cuenta', type_options: { currency: 'USD' }}
                    - { property: 'genero', type: 'text', label: 'Género'}
                    - { property: 'diasPrueba', type: 'text', label: 'Días de prueba'}
        FichaMedica:
            class: App\Entity\FichaMedica
            list:
                fields: ['alumno', 'fecha']
            form:
                fields:
                    - { property: 'fecha', type: 'date',type_options: {widget: 'single_text'}, label: 'Fecha'}
                    - { property: 'enfermedadesCardiacas',type: 'checkbox', label: '¿Posee enfermedades cardíacas?'}
                    - { property: 'lesionesCronicas',type: 'checkbox', label: '¿Posee lesiones crónicas?'}
                    - { property: 'rehabilitacion',type: 'checkbox', label: '¿Se encuentra en rehabilitación?'}
                    - { property: 'diabetes',type: 'checkbox', label: '¿Es diabético/a?'}
                    - { property: 'bajoTratamiento',type: 'checkbox', label: '¿Se encuentra bajo algún tipo de tratamiento?'}
                    - { property: 'cirugia',type: 'checkbox', label: '¿Posee cirugías?'}
                    - { property: 'sobrepeso',type: 'checkbox', label: '¿Tiene sobrepeso?'}
                    - { property: 'conoceImc',type: 'checkbox', label: '¿Conoce su IMC?'}
                    - { property: 'dieta',type: 'checkbox', label: '¿Se encuentra a dieta?'}
                    - { property: 'perderPeso',type: 'checkbox', label: '¿Se encuentra en un plan de perder peso?'}
                    - { property: 'peso', type: 'text', label: 'Peso'}                  
                    - { property: 'altura', type: 'text', label: 'Altura'}      
                    - { property: 'problemasArticulares',type: 'checkbox', label: '¿Posee problemas articulares?'}
                    - { property: 'problemasEspalda',type: 'checkbox', label: '¿Posee problemas de espalda?'}
                    - { property: 'dolores',type: 'checkbox', label: '¿Posee algún tipo de dolor crónico?'}
                    - { property: 'hipertenso',type: 'checkbox', label: '¿Es hipertenso?'}
                    - { property: 'medicamentos',type: 'checkbox', label: '¿Toma algún tipo de medicamento?'}                
                    - { property: 'listaMedicamentos', type: 'textarea', label: 'Lista de medicamentos'}  
                    - { property: 'embarazada',type: 'checkbox', label: '¿Se encuentra embarazada?'}       
                    - { property: 'tiempoEmbarazo', type: 'text', label: 'Tiempo de embarazo'}     
                    - { property: 'hernias',type: 'checkbox', label: '¿Posee algun tipo de hernia?'}
                    - { property: 'hidratado',type: 'checkbox', label: '¿Se encuentra bien hidratado?'}            
                    - { property: 'Talla', type: 'text', label: 'Talla'}                                        
                    - { property: 'listaEnfermedades', type: 'textarea', label: 'Lista de enfermedades'}
                    - { property: 'observaciones', type: 'textarea', label: 'Obervaciones particulares'}  
                    - { property: 'alumno', type: 'easyadmin_autocomplete',type_options: {class: 'App\Entity\Alumno'}, label: 'Alumno'}                              
        Telefono:
            class: App\Entity\Telefono
            list:
                fields: ['caracteristica', 'numero', 'tipo','alumno','empleado','fichaMedica']
            form:
                fields:
                    - { property: 'tipo', type: 'choice', label: 'Tipo',type_options:{choices:{'Fijo':'Fijo','Celular':'Celular'}}}
                    - { property: 'caracteristica', type: 'text', label: 'Característica'}
                    - { property: 'numero', type: 'text', label: 'Número'}                    
                    - { property: 'alumno', type: 'easyadmin_autocomplete',type_options: {class: 'App\Entity\Alumno'}, label: 'Alumno'}                   
                    - { property: 'empleado', type: 'easyadmin_autocomplete',type_options: {class: 'App\Entity\Empleado'}, label: 'Empleado'}                   
                    - { property: 'fichaMedica', type: 'easyadmin_autocomplete',type_options: {class: 'App\Entity\FichaMedica'}, label: 'Emergencia'} 
        # Entidades de Emiliano
        Empleado:
            class: App\Entity\Empleado
            list:
                fields: [ { property: 'cuit', label: 'CUIT' }, 'apellido', 'nombre']
            form:
                fields:
                    - { property: 'dni', type: 'text', label: 'DNI'}
                    - { property: 'apellido', type: 'text', label: 'Apellido'}
                    - { property: 'nombre', type: 'text', label: 'Nombres'}                    
                    - { property: 'cuit', type: 'text', label: 'CUIT'}
                    - { property: 'relacion', type: 'choice', label: 'Relación laboral',type_options:{choices:{'Monotributista':'Monotributista','En relación de dependencia':'En relación de dependencia'}}}
                    - { property: 'direccion', type: 'text', label: 'Dirección'}
                    - { property: 'fechaNacimiento', type: 'date',type_options: {widget: 'single_text'}, label: 'Fecha de nacimiento'}
        Profesor:
            class: App\Entity\Profesor
        # Entidades de Maty
        # Entidades de Maxi
        Actividad:
            class: App\Entity\Actividad
            list:
                fields: ['nombre', 'grupal', 'descripcion','estado', { property: 'fechaInicio', label: 'Fecha de inicio de actividad' }]
            form:
                fields:
                    - { property: 'nombre', type: 'text', label: 'Nombre'}
                    - { property: 'grupal', type: 'checkbox', label: '¿Es grupal?'}
                    - { property: 'fechaInicio', type: 'date', label: 'Fecha de creación de la actividad',type_options: {widget: 'single_text'}}                    
                    - { property: 'estado', type: 'checkbox', label: '¿Se realiza actualmente?'}
                    - { property: 'descripcion', type: 'textarea', label: 'Descripción'}
        Equipamiento:
            class: App\Entity\Equipamiento
            list:
                fields: ['descripcion', 'estado',  { property: 'fechaAdquisicion', label: 'Fecha de adquisición' }, { property: 'proxMantenimiento', label: 'Fecha de próx. mantenimiento' }, { property: 'MantenimientoDias', label: 'Días entre mantenimientos' }]
            form:
                fields:
                    - { property: 'descripcion', type: 'text', label: 'Descripcion'}
                    - { property: 'estado', type: 'choice', label: 'Descripcion',type_options:{choices:{'En mantenimiento':'En mantenimiento','Listo para usar':'Listo para usar'}}}
                    - { property: 'fechaAdquisicion', type: 'date', label: 'Fecha de adquisición',type_options: {widget: 'single_text'}}
                    - { property: 'proxMantenimiento', type: 'date', label: 'Fecha del próximo mantenimiento',type_options: {widget: 'single_text'}}
                    - { property: 'MantenimientoDias', type: 'text', label: 'Periodicidad del mantenimiento'}  
        Elemento:
            class: App\Entity\Elemento
            list:
                fields: ['descripcion', 'cantidad', { property: 'proxMantenimiento', label: 'Fecha de próx. mantenimiento' }, { property: 'MantenimientoDias', label: 'Días entre mantenimientos' }]
            form:
                fields:
                    - { property: 'descripcion', type: 'text', label: 'Descripcion'}
                    - { property: 'proxMantenimiento', type: 'date', label: 'Fecha del próximo mantenimiento',type_options: {widget: 'single_text'}}
                    - { property: 'MantenimientoDias', type: 'text', label: 'Periodicidad del mantenimiento'}                    
                    - { property: 'cantidad', type: 'text', label: 'Cantidad disponible'}
    list:
 
        actions: ['show']
