easy_admin:
    entities:
        # change the following to the namespaces of your own entities
        - App\Entity\Cliente
        - App\Entity\FichaMedica
        - App\Entity\Empleado
    list:
        actions: ['show']
