easy_admin:
    site_name: 'Fussion Fitnnes Gym'
    entities:
        # change the following to the namespaces of your own entities
        - App\Entity\User
        # Entidades de Damian
        # Entidades de Emiliano
        - App\Entity\Empleado
        - App\Entity\Profesor
        # Entidades de Maty
        # Entidades de Maxi

 
    list:
 
        actions: ['show']
