easy_admin:
    site_name: 'Fussion Fitnnes Gym'
    design:
        brand_color: '#e2048d'
        menu:
            # Entidades de Damian A
            - label: 'Gestión de alumnos'
              icon: 'address-card'
              children:
                - { entity: 'Alumno', icon: 'address-card' }
                - { entity: 'FichaMedica', icon: 'clipboard' }
                - { entity: 'Telefono', icon: 'phone' }
            # Entidades de Maxi
            - { entity: 'Actividad', icon: 'bolt' }
            - label: 'Gestión de elementos'
              icon: 'cogs'
              children:
                - { entity: 'Equipamiento', icon: 'cogs' }
                - { entity: 'Elemento', icon: 'list' }
            # Entidades de Emiliano
            - label: 'Gestión de Empleados'
              icon: 'users'
              children:
                - { entity: 'Empleado', icon: 'users' }
                - { entity: 'Profesor', icon: 'user' }
                - { entity: 'Telefono', icon: 'phone' }
            # Entidades de Matias
            - { label: "Usuarios" , entity: 'User', icon: 'child' }
            

    entities:
        # change the following to the namespaces of your own entities
        User:
            class: App\Entity\User 
        # Entidades de Damian
        Alumno:
            class: App\Entity\Alumno
        FichaMedica:
            class: App\Entity\FichaMedica
        Telefono:
            class: App\Entity\Telefono
        # Entidades de Emiliano
        Empleado:
            class: App\Entity\Empleado
            form:
                fields:
                    - { property: 'dni', type: 'text', label: 'DNI'}
                    - { property: 'apellido', type: 'text', label: 'Apellido'}
                    - { property: 'nombre', type: 'text', label: 'Nombres'}                    
                    - { property: 'cuit', type: 'text', label: 'CUIT'}
                    - { property: 'relacion', type: 'text', label: 'Relación laboral'}
                    - { property: 'direccion', type: 'text', label: 'Dirección'}
                    - { property: 'fechaNacimiento', type: 'date',type_options: {widget: 'single_text'}, label: 'Fecha de nacimiento'}
        Profesor:
            class: App\Entity\Profesor
        # Entidades de Maty
        # Entidades de Maxi
        Actividad:
            class: App\Entity\Actividad
        Equipamiento:
            class: App\Entity\Equipamiento
        Elemento:
            class: App\Entity\Elemento
    list:
 
        actions: ['show']
