easy_admin:
    site_name: 'Fussion Fitnnes Gym'
    design:
        brand_color: '#e2048d'
        menu:
            # Entidades de Damian
            # Entidades de Emiliano
            # Entidades de Maty
            - { entity: 'User', icon: 'child' }
            # Entidades de Maxi

    entities:
        # change the following to the namespaces of your own entities
        - App\Entity\User
        # Entidades de Damian
        # Entidades de Emiliano
        - App\Entity\Empleado
        - App\Entity\Profesor
        # Entidades de Maty
        # Entidades de Maxi

 
    list:
 
        actions: ['show']
